// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVtvCqSNMr5ztEDaKhhOTtLOl3MyCseZ8',
    appId: '1:516492055753:web:8245e44d1bb3f3fbf86918',
    messagingSenderId: '516492055753',
    projectId: 'instagram-clone-f2181',
    authDomain: 'instagram-clone-f2181.firebaseapp.com',
    storageBucket: 'instagram-clone-f2181.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMuxIz7e1JhVvNKGsvfa5vZfWzGs_QxeM',
    appId: '1:516492055753:android:f8a5dada27d7e2fcf86918',
    messagingSenderId: '516492055753',
    projectId: 'instagram-clone-f2181',
    storageBucket: 'instagram-clone-f2181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_hX-xteDsOGXLijxlz34aHqLONtgC2LI',
    appId: '1:516492055753:ios:217b1e6ab60a75c3f86918',
    messagingSenderId: '516492055753',
    projectId: 'instagram-clone-f2181',
    storageBucket: 'instagram-clone-f2181.firebasestorage.app',
    iosClientId: '516492055753-f0amms139nqie7nhh8l0l8stq8gu86ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_hX-xteDsOGXLijxlz34aHqLONtgC2LI',
    appId: '1:516492055753:ios:217b1e6ab60a75c3f86918',
    messagingSenderId: '516492055753',
    projectId: 'instagram-clone-f2181',
    storageBucket: 'instagram-clone-f2181.firebasestorage.app',
    iosClientId: '516492055753-f0amms139nqie7nhh8l0l8stq8gu86ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVtvCqSNMr5ztEDaKhhOTtLOl3MyCseZ8',
    appId: '1:516492055753:web:e1cb55d0bd3e98ccf86918',
    messagingSenderId: '516492055753',
    projectId: 'instagram-clone-f2181',
    authDomain: 'instagram-clone-f2181.firebaseapp.com',
    storageBucket: 'instagram-clone-f2181.firebasestorage.app',
  );
}
